In [1]:
import numpy as np

###### Creating a Matrix using Numpy

In [2]:
matrix_1 = np.array(([1,2,3],[4,5,6]))
print(matrix_1)

[[1 2 3]
 [4 5 6]]


In [3]:
matrix_1.shape 

(2, 3)

In [4]:
matrix_2 = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(matrix_1)

[[1 2 3]
 [4 5 6]]


In [5]:
matrix_2.shape

(3, 3)

###### Creating metrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.81941583 0.03873546 0.57062459]
 [0.90627032 0.72747659 0.43376276]
 [0.45330959 0.08228261 0.4218764 ]]


In [7]:
#creating matrix with random integers
random_matrix_integers = np.random.randint(100, size= (4,5))
print(random_matrix_integers)

[[82 42 24 36 35]
 [33 43 58  8 79]
 [44 83 15 65 32]
 [95 44 61 87 38]]


###### Matrix with all the values as 1

In [8]:
matrix_2 = np.ones((3,3))

In [9]:
print(matrix_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matrix_3 = np.ones((10,10), dtype = int)

In [11]:
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [12]:
matrix_4 = np.zeros((7,7))
print(matrix_4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


###### Identity Matrix 

In [13]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###### Transpose of a matrix

In [14]:
#matrix with random integer values
a = np.random.randint(3,5,(4,5))
print(a)

[[3 3 4 3 3]
 [3 4 3 4 4]
 [4 3 3 3 4]
 [3 4 3 3 4]]


In [15]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[3 3 4 3]
 [3 4 3 4]
 [4 3 3 3]
 [3 4 3 3]
 [3 4 4 4]]


###### Matrix Addition

###### Two Matrices can be added  only if they have the same shape

In [17]:
#creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [18]:
print(A)

[[2 3]
 [4 5]]


In [19]:
print(B)

[[6 7]
 [8 9]]


In [20]:
A.shape

(2, 2)

In [21]:
B.shape

(2, 2)

In [23]:
#Adding two matrices
sum = A+B

In [24]:
print(sum)

[[ 8 10]
 [12 14]]


In [31]:
#creating two matrices with random values
matrix_1 = np.random.randint(10, size = (3,3))
matrix_2 = np.random.randint(20, size = (3,3))

In [33]:
print(matrix_1)

[[6 1 6]
 [0 5 5]
 [3 3 7]]


In [34]:
print(matrix_2)

[[ 9 14 17]
 [14  5 13]
 [ 3 13 15]]


In [35]:
sum = np.add(matrix_1, matrix_2)

In [36]:
print(sum)

[[15 15 23]
 [14 10 18]
 [ 6 16 22]]


In [37]:
#creating two matrices with random values
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [38]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different###### 

###### Matrix Subtraction

In [39]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [40]:
print(A)

[[2 3]
 [4 5]]


In [41]:
print(B)

[[6 7]
 [8 9]]


In [43]:
difference = A - B

In [44]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [45]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [46]:
print(matrix_1)

[[0 0 3]
 [2 2 5]
 [1 4 3]]


In [47]:
print(matrix_2)

[[17  7 16]
 [ 4  6  4]
 [ 4  5  9]]


In [48]:
diff = np.subtract(matrix_1, matrix_2)

In [49]:
print(diff)

[[-17  -7 -13]
 [ -2  -4   1]
 [ -3  -1  -6]]


###### Multiplying a matrix by a scalar

In [50]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[1 1 2 7]
 [1 3 5 9]
 [3 6 6 7]
 [8 2 0 9]]


In [51]:
product = np.multiply(x,y)

In [52]:
print(product)

[[ 5  5 10 35]
 [ 5 15 25 45]
 [15 30 30 35]
 [40 10  0 45]]


###### Multiplying 2 Matrices

In [53]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [54]:
print(matrix_3)

[[0 4 2]
 [2 4 1]
 [2 3 3]]


In [55]:
print(matrix_4)

[[0 3 2 0]
 [4 3 1 0]
 [0 4 1 3]]


In [56]:
product = np.dot(matrix_3, matrix_4)

In [57]:
print(product)

[[16 20  6  6]
 [16 22  9  3]
 [12 27 10  9]]


In [58]:
product.shape

(3, 4)

In [59]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [60]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

###### Element wise Matrix Multiplication

In [61]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [62]:
print(matrix_3)

[[2 4 2]
 [2 4 3]
 [4 2 0]]


In [63]:
print(matrix_4)

[[1 3 0]
 [4 4 2]
 [3 4 1]]


In [64]:
product = np.multiply(matrix_3, matrix_4)

In [65]:
print(product)

[[ 2 12  0]
 [ 8 16  6]
 [12  8  0]]


In [66]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [67]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 